#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          43

bspc config focused_border_color "#a6d189" 
bspc config normal_border_color "#85c1dc"
bspc config active_border_color "#cba6f7"
bspc config presel_feedback_color "#a6d189"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Vivaldi-stable desktop='^2' follow=on focus=on
bspc rule -a Brave-browser desktop='^3' follow=on focus=on
bspc rule -a Nemo desktop='^3' follow=on focus=on
bspc rule -a discord desktop='^6' follow=on focus=on

# StartUp Apps
ibus-daemon -drx

# Power Manager
xfce4-power-manager

# Picom
picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &

# Polkit
/usr/lib/xfce-polkit/xfce-polkit &

# Wallpaper
nitrogen --restore &

# Notification
dunst &

# Cursor
xsetroot -cursor_name left_ptr

# Polybar
$HOME/.config/bspwm/polybar/launch.sh

# Java Apps
export _JAVA_AWT_WM_NONREPARENTING=1

